# Generated by Django 6.1 on 2026-08-15 22:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CORRETORA', 'Corretora'), ('FRIA', 'Carteira fria (Hardware)'), ('WEB', 'Carteira web (Hot Wallet)'), ('PROPRIA', 'Carteira própria')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=10, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('preco_atual', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=24)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_operacao', models.DateTimeField()),
                ('tipo_operacao', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('TRANSF_REC', 'Transferência recebida'), ('TRANSF_ENV', 'Transferência enviada'), ('AIRDROP', 'Airdrop'), ('STAKING', 'Staking'), ('RECOMPENSA', 'Recompensa'), ('OUTRO', 'Outro')], max_length=15)),
                ('quantidade', models.DecimalField(decimal_places=8, max_digits=24)),
                ('preco_unitario', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=24)),
                ('taxa', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=24)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('corretora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='carteira.corretora')),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='carteira.moeda')),
            ],
        ),
    ]
