# Generated by Django 6.1 on 2026-08-16 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='corretora',
        ),
        migrations.RemoveField(
            model_name='moeda',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='moeda',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='moeda',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='data_operacao',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='taxa',
        ),
        migrations.AddField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moeda',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='preco_atual',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='moeda',
            name='simbolo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo_operacao',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='valor_total',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Corretora',
        ),
    ]
