# Generated by Django 6.1 on 2026-08-16 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0002_remove_transacao_corretora_remove_moeda_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
