# Generated by Django 6.1 on 2026-08-17 01:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira', '0003_alter_transacao_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('valor_total', models.FloatField()),
            ],
        ),
    ]
